config/routes.rb
Qtag::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match ':user_hash', to: 'users#show_hash', as: :hashtag

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :description, :hashtag, :name, :image
  validates :user_id, presence: true
  validates :name, presence: true

  belongs_to :user
  has_attached_file :image, :storage => :s3, :s3_credentials => S3_CREDENTIALS #, :s3_credentials => "#{Rails.root}/config/s3.yml"

  before_create :create_and_assign_hashtag

  private

  def create_and_assign_hashtag
    hashtag = SecureRandom.urlsafe_base64(6)
    self.hashtag = hashtag
    code = "http://qtag.herokuapp.com/" + hashtag
    qr = RQRCode::QRCode.new(code, :size => 5)
    image = qr.to_image(5)
    temp_file = Tempfile.new([hashtag, '.png'])
    temp_file.write image
    temp_file.flush
    self.image = temp_file
    temp_file.close
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :tags, dependent: :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  after_create :create_tag

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def create_tag
      self.tags.create(name: "This is the TAG name. Please edit.", description: "This is a long description. Please edit as needed.")
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    @title = "Sign in"
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @title = "Home"
  end

  def help
    @title = "Help"
  end

  def about
    @title = "About Us"
  end

  def contact
    @title = "Contact"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,   only: [:edit, :update]
  before_filter :admin_user,     only: :destroy


  def index
    @title = 'All users'
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = "#{@user.name}"
    @tags = @user.tags
  end
  
  def show_hash
    hashtag = params[:user_hash]
    @tag = Tag.find_by_hashtag hashtag
    if !@tag
      flash[:error] = "The Qtag #{hashtag} does not exist."
      redirect_to root_path
    end
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
     sign_in @user
     flash[:success] = "Welcome to Qtag App!"
     redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
      if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end      
end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'RQRCode/QRCode'
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://qtag.herokuapp.com/">Qtag Application</a>
    by Juan Pieres
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://qtag.herokuapp.com/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "QTAG", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qtag application | <%= @title %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
  The <a href="http://qtag.herokuapp.com//">Qtag Spain</a>
  is a project to make .......
</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Qtaq at
  <a href="http://qtag.herokuapp.com/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to qtag Spain</h1>

  <h2>
    This is the home page for the
    <a href="http://qtag.herokuapp.com/">qtag</a>
    application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/tags/_tag.html.erb
<li>
<h2><%= tag.name %></h2>
  <span class="name"><%= tag.description %></span>
  <span class="timestamp name">
    Created <%= time_ago_in_words(tag.created_at) %> ago.
  </span>
  <%= image_tag tag.image %>
</li>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= "Tags for #{@user.name}" %></h1>
  <% if @user.tags.any? %>
    <h3>Tags (<%= @user.tags.count %>)</h3>
    <ol class="tags">
      <%= render @tags %>
    </ol>
  <% end %>

app/views/users/show_hash.html.erb
<h1><%= @tag.name %></h1>
<h3>Tag: <%= @tag.hashtag %></h3>
<h3>Description: <%= @tag.description %></h3>
<h3>Image:</h3>
<%= image_tag  @tag.image %>